#include 'totvs.ch'

FUNCTION U_NOVO_FORNECEDOR

    Local oFornecedor       as object
    Local aDados            as array

    //Pergunta cadastrada no configurador
    IF .not. pergunte('ZNOVOCGC')
        RETURN
    ENDIF

    oFornecedor             := pessoa():new()   
    oFornecedor:cpf_cnpj    := MV_PAR01 // Salva o parâmetro passado por ZNOVOCGC
    oFornecedor:get_dados_cadastrais() //Consulta os dados cadastrais

    aDados                  := array(0)

    cCodigo                 := getSxeNum('SA2','A2_COD')
    
    WHILE .T.
      SA2->(dbSetOrder(1),dbSeek(xFilial(alias())+cCodigo))
        IF Found() //verifica se o ultimo dbseek executado foi encontrado
            confirmSX8()
            cCodigo := getSxeNum('SA2','A2_COD') // Novo codigo
            LOOP
        ENDIF 
        EXIT
    END
    
    //tamSX3 = Busca tamanho do campo
    cNome                   := LEFT(oFornecedor:nome,tamSX3('A2_NOME')[1])
    cNomeReduz              := LEFT(oFornecedor:nome_reduzido,tamSX3('A2_NREDUZ')[1])
    cEndereco               := LEFT(oFornecedor:endereco,tamSX3('A2_END')[1])
    cBairro                 := LEFT(oFornecedor:bairro,tamSX3('A2_BAIRRO')[1])
    cEstado                 := LEFT(oFornecedor:uf,tamSX3('A2_EST')[1])
    cCodMun                 := LEFT(oFornecedor:cod_ibge,tamSX3('A2_COD_MUN')[1])
    cCidade                 := LEFT(oFornecedor:cidade,tamSX3('A2_MUN')[1])
    cEmail                  := LEFT(oFornecedor:email,tamSX3('A2_EMAIL')[1])
    dDataNasc               := oFornecedor:data_nascimento


    // Nil faz parte da regra de uso do MsExecAuto
    aadd(aDados,{"A2_COD"   ,cCodigo        ,Nil})
    aadd(aDados,{"A2_LOJA"  ,"01"           ,Nil})
    aadd(aDados,{"A2_TIPO"  ,"J"            ,Nil})
    aadd(aDados,{"A2_CGC"   ,MV_PAR01       ,Nil})
    aadd(aDados,{"A2_NOME"  ,cNome          ,Nil})
    aadd(aDados,{"A2_NREDUZ",cNomeReduz     ,Nil})    
    aadd(aDados,{"A2_END"   ,cEndereco      ,Nil})
    aadd(aDados,{"A2_EST"   ,cEstado        ,Nil})
    aadd(aDados,{"A2_BAIRRO",cBairro        ,Nil})
    aadd(aDados,{"A2_COD_MUN",cCodMun       ,Nil})
    aadd(aDados,{"A2_MUN"   ,cCidade        ,Nil})
    aadd(aDados,{"A2_EMAIL" ,cEmail         ,Nil})
    aadd(aDados,{"A2_DTNASC",dDataNasc      ,Nil})

    // Verificar erro
    lMsErroAuto := .F.

    //executar mata020: INCLUSAO = 3
    msExecAuto({|x| mata020(x,3)}, aDados)

    // lMsErroAuto .T.
    IF lMsErroAuto
        mostraErro()
        RETURN
    ENDIF

    //Função que confirma a numeração
    confirmSX8()

RETURN
